---
title: "Final Project (Team 7)"
author: "Sahil Wadhwa"
---

```{r}
#Packages Used

library(caret)
library(ggplot2)
library(corrplot)
library(tidyr)
library(ROSE)
library(gt)
```

```{r}
# Upload datasets
train <- read.csv("train_dataset.csv")
test <- read.csv("test_dataset.csv")

# Use train_dataset moving forward
smokedf <- train 
str(smokedf)
class(smokedf)
#summary(smokedf)
```

```{r}
# Missing Values
smokedf[smokedf == ""] <- NA
na_value <- sapply(smokedf, function(x) sum(is.na(x)))
predictors_with_missing <- names(na_value[na_value > 0])

missing_values_table <- data.frame(Predictor = predictors_with_missing,
Missing_Values = na_value[predictors_with_missing])
missing_values_table |> head() |> gt() |>
  tab_header(title = "Predictors with Missing Values")

vis_miss(smokedf)
```
```{r}
# Histogram of each predictors
smokedf |>
  pivot_longer(-Fire.Alarm, names_to = 'Element', values_to = 'value') |>
  ggplot(aes(x = value)) +
  geom_histogram(bins = 20) +
  facet_wrap(~Element, scales = 'free', ncol = 4) +  
  theme(axis.text.x = element_text(angle = 10)) +
  labs(title = 'Predictors Distribution', x = NULL, y = "Count")
```
```{r}
#Create box plots for each predictors:
smokedf |>
  pivot_longer(-Fire.Alarm, names_to = 'Element', values_to = 'value') |>
  ggplot(aes(value)) +
  geom_boxplot() +
  facet_wrap(~Element, scales = "free", ncol = 4) +
  theme(axis.text.x = element_text(angle = 10)) +
  labs(title = 'Box Plots of Predictors', x = "Count")
```
```{r}
# Create box plots of response for each predictors:
smokedf |>
  pivot_longer(-Fire.Alarm, names_to = 'Element', values_to = 'value') |>
  ggplot(aes(Fire.Alarm, value, group = Fire.Alarm)) +
  geom_boxplot() +
  facet_wrap(~Element, scales = "free", ncol = 4) +
  theme(axis.text.x = element_text(angle = 0)) +
  labs(title = 'Box Plots of Predictors over Response', x = "Fire Alarm", y = "Count")
```


```{r}
# Convert UTC format into hours of day and day of week
smokedf$UTC_datetime <- as.POSIXct(smokedf$UTC, origin = "1970-01-01", tz = "UTC")
# all from 2022 and June

smokedf$hour <- hour(smokedf$UTC_datetime)
smokedf$day <- wday(smokedf$UTC_datetime, week_start = 1)

# Reorder variables and remove UTC_datetime
other_columns <- setdiff(names(smokedf), "Fire.Alarm")
smokedf <- smokedf[, c(other_columns, "Fire.Alarm")]
smokedf <- subset(smokedf, select = c(-UTC_datetime, -UTC))
```

```{r}
# Correlation plot including outcome variable
smokedf |>
mutate(Fire.Alarm = as.numeric(Fire.Alarm)) |>
cor() |>
corrplot.mixed(title = "Correlation Plot Between Outcome and Predictors",
tl.cex = .25, number.cex = 0.6, mar = c(1, 1, 1, 1))
```

```{r}
# Remove highly correlated predictors
correlation_matrix <- cor(smokedf[, -1])
highly_correlated <- findCorrelation(correlation_matrix, cutoff = 0.75)
highly_correlated_names <- colnames(smokedf[, -1])[highly_correlated]
smokedf_reduced <- smokedf[, -highly_correlated]

# Correlation plot including outcome variable
smokedf_reduced |> 
  mutate(Fire.Alarm = as.numeric(Fire.Alarm)) |>
  cor() |>
  corrplot.mixed(title = "Reduced Correlation Plot",
                 tl.cex = .5, number.cex = 0.8, mar = c(1, 1, 1, 1))
```

```{r}
# Calculate skewness of each predictors
# Skew values less than ±0.5 should be considered ‘normal enough’
skew_fa <- smokedf_reduced |>
  dplyr::select(-Fire.Alarm) |>
  map_dbl(skewness) |> round(3) 

skew_fa_tibble <- tibble(Variable = names(skew_fa), Skewness = skew_fa)
skew_fa_tibble |> gt()

# Determine zero values in the dataframe
zero_counts <- sapply(smokedf, function(x) sum(x == 0, na.rm = TRUE))
```

```{r}
# Perform Box Cox Tranformation Analysis and determine predictors with >50% improvement
bct_test <- function(x, property = 'skew') {
  stopifnot(property %in% c('skew', 'lambda'))
  
  x <- x[which(! is.na(x))] 
  x2 <- x + ifelse(any(x == 0), 0.0001, 0) 

  bct <- BoxCoxTrans(x2)
  x_trans <- predict(bct, x2 )
if (property == 'skew') return(e1071::skewness(x_trans))
return(bct$lambda)}

skew_smfa_bct <- smokedf_reduced |>
  dplyr::select(-Fire.Alarm) |>
  map_dbl(bct_test)

bct_analysis <- tibble(
  Property = names(skew_fa),
  `Original Skew` = skew_fa,
  `Skew after BoxCox`= round(skew_smfa_bct,4),
  Lambda = smokedf_reduced |> dplyr::select(-Fire.Alarm) |> 
    map_dbl( ~ bct_test(.x, 'lambda')))

bct_keep <- bct_analysis |>
  filter(abs(`Original Skew`) > 0.5,
         abs(`Skew after BoxCox`) < 0.5)

bct_keep |>
gt::gt()

# Apply BCT Analysis result in reduced dataframe
bct <- BoxCoxTrans(smokedf_reduced$CNT + 
                     ifelse(any(smokedf_reduced$CNT == 0), 0.0001, 0))
smokedf_reduced$gamma_CNT <- predict(bct, smokedf_reduced$CNT)

# Plot Changes
smokedf_reduced |> ggplot(aes(x = gamma_CNT)) +
    geom_histogram(binwidth = 500, fill = "pink", color = "white") +
    geom_histogram(aes(x = CNT), binwidth = 500, fill = "darkgray", alpha = 10) +
    labs(title = "Histogram of Box-Cox Transformed gamma with 0")

smokedf_reduced |>
ggplot(aes(x = gamma_CNT)) +
geom_histogram(bins= 9, color = "white", fill = "pink") +
labs(title ="Histogram of Box-Cox Transformed gamma_CNT")

# Remove Original CNT in reduced dataframe
smokedf_reduced <- smokedf_reduced |> dplyr::select(-CNT) |> 
  relocate("Fire.Alarm", .after = last_col())
```




```{r}
set.seed(503)
smokedf_reduced$Fire.Alarm <- ifelse(smokedf_reduced$Fire.Alarm == 0, "No", "Yes")
smokedf_predictors <- smokedf_reduced[ ,-1]
smokedf_yield <- smokedf_reduced[ ,1]

# Split the data into training and test sets
smokedf_index <- createDataPartition(smokedf_yield, p = 0.8, list = FALSE)
smokedf_train <- smokedf_predictors[smokedf_index, ]
smokedf_test <- smokedf_predictors[-smokedf_index, ]

# Center and scaling using preProcess
smokedf_prep <- preProcess(smokedf_train, method = c("center", "scale"))

# Apply the transformation to the training data
smokedf_train_transformed <- predict(smokedf_prep, smokedf_train)
smokedf_test_transformed <- predict(smokedf_prep, smokedf_test)

# Rebalance train dataset
cat("Number of non-triggered fire alarm (No) = ", 
    sum(smokedf_train_transformed$Fire.Alarm == "No"), "\n") 
cat("Number of triggered fire alarm (Yes) =", 
    sum(smokedf_train_transformed$Fire.Alarm == "Yes"))

train_balanced <- ROSE(Fire.Alarm ~ ., data = smokedf_train_transformed)$data

rebalanced <- as.data.frame(table(train_balanced$Fire.Alarm)) 
rebalanced |> gt() |> 
  tab_header(title = "Rebalanced Fire Alarm Counts")
```

```{r}
#Model #1: KNN

set.seed(100)
knnTune <- train(Fire.Alarm ~ ., data = train_balanced,
                method = "knn",
                preProc = c("center","scale"),
                tuneGrid = data.frame(k = 1:20))

knnTune
plot(knnTune)
```
```{r}
#Model 2: MARS

set.seed(100)
marsTune <- train(Fire.Alarm ~ ., data = train_balanced,
                  method = "earth",
                  tuneGrid = expand.grid(degree = 1, nprune = 2:38))
marsTune
plot(marsTune)
```
```{r}
#Predictors and Confusion Matrix for KNN

test_predictors <- smokedf_test_transformed[, -8]
test_org <- data.frame(Fire.Alarm = smokedf_test_transformed$Fire.Alarm)
test_org$Fire.Alarm <- factor(test_org$Fire.Alarm)

knn_predictions <- predict(knnTune, newdata = test_predictors, type = "raw")
knn_predictions <- data.frame(Fire.Alarm = knn_predictions)

cm_knn <- confusionMatrix(data = as.factor(knn_predictions$Fire.Alarm),
                               reference = test_org$Fire.Alarm, positive = "Yes")
cm_knn
```


```{r}
#Predictors and Confusion Matrix for Mars

mars_predictions <- predict(marsTune, newdata = test_predictors, type = "raw")
mars_predictions <- data.frame(Fire.Alarm = mars_predictions)

cm_mars <- confusionMatrix(data = as.factor(mars_predictions$Fire.Alarm),
                               reference = test_org$Fire.Alarm, positive = "Yes")
cm_mars
```

#Performance Evaluation of KNN

```{r}
#Accuracy of 0.835
```

#Performance Evaluation of MARS

```{r}
#Accuracy of 0.757
```







